language: node_js

node_js:
  - "5.1"

sudo: required

services:
  - docker

before_install:
- docker pull couchbase/server:4.5.0-DP1
- docker run -d -p 8091-8093:8091-8093 couchbase/server:4.5.0-DP1 --name couchbase
- docker ps -a 
