language: node_js

node_js:
  - "5.1"

sudo: required

services:
  - docker

before_install:
- docker pull couchbase/server:4.5.0-DP1
- docker run -d --name couchbase couchbase/server:4.5.0-DP1
- docker ps -a 


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
